name: Samantha Ross
favicon: null
layout_spectrum: 0.4517027516849339
typography_spectrum: 0.12984380684792995
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.08603725722059608
  lightness: 0.13954288745298982
  saturation: 0.9591920301318169
  rhythmicContrast: 0.10317962244153023
purpose: []
